### PR TITLE
Add Metachain Testnet

### PR DESCRIPTION
**Pull request by swarna1101**

### CODE REVIEW

**Comment by swarna1101** [comment]
Hi @igorbarinov , can you take a look and close this issue soon? Looking forward to it.

**Comment by andogro** [comment]
@swarna1101 do you have a Blockscout instance we can add - we link to instances for the testnet rather than project web pages.

**Comment by swarna1101** [comment]
Yes @andogro , 
Link - https://blockscout.testnet.ocean.jellyfishsdk.com/

**Comment by andogro** [comment]
We are no longer updating this page. Please add your project to this airtable and we will add to the new site. Thanks https://airtable.com/appei1B8KwfA8kfol/pag9lBN2gDqhVSom7/form

**Pull request closed without merging**
