### PR TITLE
Add env variable for Celestia blobs indexer URL

### PR DESCRIPTION
**Pull request by varasev**
Relates to https://github.com/blockscout/blockscout/pull/10199

### CODE REVIEW

**Review by vbaranov — COMMENTED** [review]
@varasev we should reflect removal of these env variables:
```
In part of env variables optimization, the following ones were removed:

INDEXER_OPTIMISM_L1_PORTAL_CONTRACT
INDEXER_OPTIMISM_L1_DEPOSITS_START_BLOCK
INDEXER_OPTIMISM_L1_WITHDRAWALS_START_BLOCK
INDEXER_OPTIMISM_L1_OUTPUT_ROOTS_START_BLOCK
INDEXER_OPTIMISM_L1_BATCH_START_BLOCK
INDEXER_OPTIMISM_L1_BATCH_INBOX
INDEXER_OPTIMISM_L1_BATCH_SUBMITTER
```

in https://docs.blockscout.com/for-developers/information-and-settings/env-variables/deprecated-env-variables

**Comment by varasev** [comment]
> @varasev we should reflect removal of these env variables:
> 
> ```
> In part of env variables optimization, the following ones were removed:
> 
> INDEXER_OPTIMISM_L1_PORTAL_CONTRACT
> INDEXER_OPTIMISM_L1_DEPOSITS_START_BLOCK
> INDEXER_OPTIMISM_L1_WITHDRAWALS_START_BLOCK
> INDEXER_OPTIMISM_L1_OUTPUT_ROOTS_START_BLOCK
> INDEXER_OPTIMISM_L1_BATCH_START_BLOCK
> INDEXER_OPTIMISM_L1_BATCH_INBOX
> INDEXER_OPTIMISM_L1_BATCH_SUBMITTER
> ```
> 
> in https://docs.blockscout.com/for-developers/information-and-settings/env-variables/deprecated-env-variables

Maybe it's better to make a note `Removed in v...` in `Deprecated in Version` column? I think, we shouldn't remove them from the doc to let users of old versions have the descriptions

**Comment by vbaranov** [comment]
> https://docs.blockscout.com/for-developers/information-and-settings/env-variables/deprecated-env-variables

https://docs.blockscout.com/for-developers/information-and-settings/env-variables/deprecated-env-variables page was made specifically for variables which are unsupported in the latest version of the backend. We keep description for the variables and the version where deprecation happened. We can add a note with the link to that "deprecated variables" page here  https://docs.blockscout.com/for-developers/information-and-settings/env-variables/backend-envs-chain-specific#optimism-rollup-management to increase the visibility of that page for users.

**Comment by varasev** [comment]
> > https://docs.blockscout.com/for-developers/information-and-settings/env-variables/deprecated-env-variables
> 
> https://docs.blockscout.com/for-developers/information-and-settings/env-variables/deprecated-env-variables page was made specifically for variables which are unsupported in the latest version of the backend. We keep description for the variables and the version where deprecation happened. We can add a note with the link to that "deprecated variables" page here https://docs.blockscout.com/for-developers/information-and-settings/env-variables/backend-envs-chain-specific#optimism-rollup-management to increase the visibility of that page for users.

Ok. What version should be in `Deprecated in Version` column for these variables? Is it ok if I point `master` there for now?

**Comment by varasev** [comment]
> @varasev we should reflect removal of these env variables:
> 
> ```
> In part of env variables optimization, the following ones were removed:
> 
> INDEXER_OPTIMISM_L1_PORTAL_CONTRACT
> INDEXER_OPTIMISM_L1_DEPOSITS_START_BLOCK
> INDEXER_OPTIMISM_L1_WITHDRAWALS_START_BLOCK
> INDEXER_OPTIMISM_L1_OUTPUT_ROOTS_START_BLOCK
> INDEXER_OPTIMISM_L1_BATCH_START_BLOCK
> INDEXER_OPTIMISM_L1_BATCH_INBOX
> INDEXER_OPTIMISM_L1_BATCH_SUBMITTER
> ```
> 
> in https://docs.blockscout.com/for-developers/information-and-settings/env-variables/deprecated-env-variables

Done in https://github.com/blockscout/docs/pull/292/commits/bbef31ebaeaac7229a4f9f47b66aa8e895898ffb. I set `Deprecated in Version` column to `master` for these vars

**Review by vbaranov — APPROVED** [review]

**Pull request merged**
