### PR TITLE
remove `make start` on ETHEREUM_JSONRPC_VARIANT example

### PR DESCRIPTION
**Pull request by hadv**

### CODE REVIEW

**Comment by vbaranov** [comment]
@hadv I think there is no issue here because it is an example of how to run the script with specified ENV var, no?

**Comment by hadv** [comment]
@vbaranov I don't think so. `ETHEREUM_JSONRPC_VARIANT` is to set ethereum client only.

**Comment by vbaranov** [comment]
> ETHEREUM_JSONRPC_VARIANT is to set ethereum client only.

That is correct. And in case of ganache JSON RPC variant, we don't need to specify anything else, right? Therefore `ETHEREUM_JSONRPC_VARIANT=ganache make start` is a correct directive. Moreover, the warning which is behind this example is about `make start` command. This makes me think, that `make start` is intentionally written in the example. otherwise, the warning should be moved somewhere else.

**Comment by hadv** [comment]
> > ETHEREUM_JSONRPC_VARIANT is to set ethereum client only.
> 
> That is correct. And in case of ganache JSON RPC variant, we don't need to specify anything else, right? Therefore `ETHEREUM_JSONRPC_VARIANT=ganache make start` is a correct directive. Moreover, the warning which is behind this example is about `make start` command. This makes me think, that `make start` is intentionally written in the example. otherwise, the warning should be moved somewhere else.

I think that `make start` is command to execute make file to build and run docker then it cannot be put into `ETHEREUM_JSONRPC_VARIANT` env variable. I think it's typo. You can refer to below line 

https://github.com/blockscout/docs/pull/25/files#diff-6d5fb5d2d64923397af60638bd8341f3L20

**Comment by vbaranov** [comment]
@hadv 

> I think that make start is command to execute make file to build and run docker then it cannot be put into ETHEREUM_JSONRPC_VARIANT env variable. I think it's typo. You can refer to below line

`ETHEREUM_JSONRPC_VARIANT=ganache make start` is not putting "make start" into env var. It is an example of running command and at the same time specifying of ETHEREUM_JSONRPC_VARIANT=ganache env var for the run. please take a look https://unix.stackexchange.com/questions/56444/how-do-i-set-an-environment-variable-on-the-command-line-and-have-it-appear-in-c

**Comment by hadv** [comment]
@vbaranov ah, I understand but I update the PR to make it more clearly! ;)

**Review by vbaranov — APPROVED** [review]

**Pull request merged**
